# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheatd < Formula
  desc "Personal cheat sheet management CLI with web interface"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.0/cheatd-darwin-amd64.tar.gz"
      sha256 "32981f11cb013a9cc4cf252b8743fd680a2ddaf6703b24275655c5082999c84f"

      def install
        bin.install "cheatd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.0/cheatd-darwin-arm64.tar.gz"
      sha256 "60a1aa4e5c0760c750ad3ee0e795d32b804f16ca2d2d6b02f5bcbc6f99e04d1d"

      def install
        bin.install "cheatd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.0/cheatd-linux-amd64.tar.gz"
      sha256 "24e029ffc8e769afa68b9e3d44f5cf06d242fe6ba28244e307c624f8ae9d2b25"
      def install
        bin.install "cheatd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.0/cheatd-linux-arm64.tar.gz"
      sha256 "3aeb9cdc4764ec27ec1a7ccd1453faf3a689c84f0863f1ff26dc9fe64227067d"
      def install
        bin.install "cheatd"
      end
    end
  end
end
