# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cheatd < Formula
  desc "Personal cheat sheet management CLI with web interface"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.3.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.3/cheatd-darwin-amd64.tar.gz"
      sha256 "78cf89882983a260f8a351b9984fd4990277b512166c94dac14f4bd593cc6145"

      def install
        bin.install "cheatd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.3/cheatd-darwin-arm64.tar.gz"
      sha256 "13dfcda6a3bc352e3703d57d52890c3053a8457cfceb14e95a626fe68181f59d"

      def install
        bin.install "cheatd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.3/cheatd-linux-amd64.tar.gz"
      sha256 "8b411f924ed1929f36f2ad794c86fc22bd7aa8f2054fef4aee675597841e7a53"
      def install
        bin.install "cheatd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.3.3/cheatd-linux-arm64.tar.gz"
      sha256 "7c4c32a7240a06bfa86d430ce4017106527c55b5c7dcd945f75cb84c61688243"
      def install
        bin.install "cheatd"
      end
    end
  end
end
