# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gophersay < Formula
  desc ""
  homepage "https://github.com/svanhalla/homebrew-tools"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/gophersay/releases/download/v1.0.8/gophersay_Darwin_arm64.tar.gz"
      sha256 "f557f146d9ff6e34b98a6f01b6d9e531359195c5fec61c01c160fd55bcaa5529"

      def install
        bin.install "gophersay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/gophersay/releases/download/v1.0.8/gophersay_Darwin_x86_64.tar.gz"
      sha256 "07c00a613926453b0509f0e124eac1bca537178e1023aa44f2739ffba004554b"

      def install
        bin.install "gophersay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/gophersay/releases/download/v1.0.8/gophersay_Linux_arm64.tar.gz"
      sha256 "d4051297d13080698c69ecc294467945234dd5bc6e8dcae240df23e475a7d97d"

      def install
        bin.install "gophersay"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/gophersay/releases/download/v1.0.8/gophersay_Linux_x86_64.tar.gz"
      sha256 "bda0f065f33d7379306bbc12debbcca79cde5ec51ab933a5460aa184dbec112d"

      def install
        bin.install "gophersay"
      end
    end
  end
end
