# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class IbUi < Formula
  desc ""
  homepage "https://github.com/svanhalla/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/ib-ui/releases/download/v0.0.1/ib-ui_Darwin_x86_64.tar.gz"
      sha256 "dd64d926854ea1f30e8398efe862ff2efacfed02e2ee60c0faa93717082d1bff"

      def install
        bin.install "ib-ui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/ib-ui/releases/download/v0.0.1/ib-ui_Darwin_arm64.tar.gz"
      sha256 "3aa4927b96e1d3d8a9cfebca5d537b2920a275d5539eb925bf2e31cc10dc75f6"

      def install
        bin.install "ib-ui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/ib-ui/releases/download/v0.0.1/ib-ui_Linux_arm64.tar.gz"
      sha256 "09ff4b4902fad7dc64caf6a72520a9fb4271e585481a714164fd511da7d4d4cc"

      def install
        bin.install "ib-ui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/ib-ui/releases/download/v0.0.1/ib-ui_Linux_x86_64.tar.gz"
      sha256 "62291a4a6f6f17e7fcd96019281198ac6683652c3c99010eca857a3489eca274"

      def install
        bin.install "ib-ui"
      end
    end
  end
end
