# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyToolBrew < Formula
  desc ""
  homepage "https://github.com/svanhalla/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/my-tool/releases/download/0.0.1/my-tool_Darwin_x86_64.tar.gz"
      sha256 "dac85b474b15185c8f96c5b91ba6d0cb3919439cec8483d1a0c933166366b06f"

      def install
        bin.install "my-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/my-tool/releases/download/0.0.1/my-tool_Darwin_arm64.tar.gz"
      sha256 "75c7a00e85ed973564373ec24ceab62cfc92da457853f098840ccf61977dfb2e"

      def install
        bin.install "my-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/my-tool/releases/download/0.0.1/my-tool_Linux_x86_64.tar.gz"
      sha256 "fbe8702c34a9238d2208528447dc0480662be4943e032cd397a10f7270f6efa2"

      def install
        bin.install "my-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/my-tool/releases/download/0.0.1/my-tool_Linux_arm64.tar.gz"
      sha256 "57aa492e8737d5df8ebb11232d92b236b98b1f7ae3af66a9b37c05f4c7e47c7f"

      def install
        bin.install "my-tool"
      end
    end
  end
end
