# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SvanhallaCli < Formula
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.7/svanhalla-cli-darwin-amd64.tar.gz"
      sha256 "9a0b80e71350a20d0d95a3acaa0268d5e75ac994bd7514357f0240bfdccd655f"

      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.7/svanhalla-cli-darwin-arm64.tar.gz"
      sha256 "7cb84d9c595c754f631a3218f4005c86e982dd87f21821c22970b2b431c53cb9"

      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.7/svanhalla-cli-linux-amd64.tar.gz"
      sha256 "99346db27f43f7950d9f76e1ff8f196682af095b90cd1661a0a75b26cc62b7e7"
      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.7/svanhalla-cli-linux-arm64.tar.gz"
      sha256 "222e57f0dbb21c3b73763fc1ef45d52fe954b3eefb282ae9ce9712c8b1fcc6a5"
      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  test do
    system "#{bin}/svanhalla-cli version"
  end
end
