# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SvanhallaCli < Formula
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.8/svanhalla-cli-darwin-amd64.tar.gz"
      sha256 "967c22da79f12230b6ab5d283cdc03f3fc52de0b7987f6700693c24eb61bf27c"

      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.8/svanhalla-cli-darwin-arm64.tar.gz"
      sha256 "2cdc4d7ebc91933428feeec50dbacbfa7c08b6a4a988e0c1fb015f8cb7ebac2a"

      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.8/svanhalla-cli-linux-amd64.tar.gz"
      sha256 "1834ce05077c12343b73b47bdf5abdd5f161611648228903075480a88415f5d5"
      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.8/svanhalla-cli-linux-arm64.tar.gz"
      sha256 "0f836757c8cb53e5384a576b5fca9681816213c825d41908145075135c2f0e01"
      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  test do
    system "#{bin}/svanhalla-cli version"
  end
end
