# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SvanhallaCli < Formula
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.6/svanhalla-cli-darwin-amd64.tar.gz"
      sha256 "fda7e290bbae543101d0d8b1690d2864b3f9cf7eb7d23090d2ebd603f6697081"

      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.6/svanhalla-cli-darwin-arm64.tar.gz"
      sha256 "a40a358c1bd54080a6372b55a2d355d17702686dfdcfc55d1a965146c47806a9"

      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.6/svanhalla-cli-linux-amd64.tar.gz"
      sha256 "a7542f18e98fc3f7188f0ffcccedb2fa4fc644a864f854e991c62ea2aa70b36c"
      def install
        bin.install "svanhalla-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v1.2.6/svanhalla-cli-linux-arm64.tar.gz"
      sha256 "921cfaabe647fa2011eaa04edc4e9a1eb8c86ca5f8ee3d7caafc970349d58c48"
      def install
        bin.install "svanhalla-cli"
      end
    end
  end

  test do
    system "#{bin}/svanhalla-cli version"
  end
end
