# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheatd" do
  name "cheatd"
  desc "Personal cheat sheet management CLI with web interface"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheatd"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "0a87bb0c750af4e3a133012c8fa820c5fc1e0353a70b87ea3dd25dca1120a59a"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "43b6f8fc496fe639438dd26eb432e708840ca1f3a4744b885ecf69aea5f3a2d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "15da19af16abd67c116f9ce021f81802b64e9b93cf6bb2641acf11a2b0b22aed"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "305a8f2ff8a7441f5e9c6d8d880f3907d62c3b367d43e4659ce819dd3193d401"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheatd"]
    end
  end

  # No zap stanza required
end
