# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheatd" do
  name "cheatd"
  desc "Personal cheat sheet management CLI with web interface"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheatd"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "8d7299652982485d7cd1e2fc61ff9125583c78118a5f7ee165c496ddb07103d4"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "3ae91755bdb999f550458144c3d5d67f49ec6cfcb0b72c056698648adb60e6d6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "4dd8e61854aaf1852b61249a1ab08805956f77bf9ff890f828d1c44b73e029f2"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "82027e13d3e286622ee259e16e140793cf9f96b4f43e7bff08439ceeca0697ac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheatd"]
    end
  end

  # No zap stanza required
end
