# This file was generated by GoReleaser. DO NOT EDIT.
cask "cheatd" do
  name "cheatd"
  desc "Personal cheat sheet management CLI with web interface"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cheatd"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "9a45655b0bae684f8ff1c40b960be036f64ef02f4dcd829c5d4ddcec9e498d98"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "a83044ac366c9b42dd6f701e361a572e198f96169fa771d22828abb2fb81cd3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "0bf67459f008998259c63cde309a5f2cfd6bf1e4df2f3d4906bf78df5c8b7af2"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/cheatd-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "6aa4ae1af73949d4d673e296acd5223e5d866973e682fb644befc4b324ed5c59"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cheatd"]
    end
  end

  # No zap stanza required
end
