# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelly" do
  name "shelly"
  desc "Modern CLI for controlling Shelly smart devices"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelly"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "d35d6a20f3c4c972857f042f5a094d98c3a9e83f191fcb144444cde81db781c3"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "d5b6caa35c4268c72304330fa99e09ca49551e801efab6ed878364621f8b5711"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "fad5951a5ca1a2181571604de7540569ff84f510410f64c807bc0189ff9e335e"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "526bd3dd9a30c4129b7d44ca0503fe0960afea839cf19ba792786253d2179ebc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelly"]
    end
  end

  # No zap stanza required
end
