# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelly" do
  name "shelly"
  desc "Modern CLI for controlling Shelly smart devices"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelly"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "1342466bf8c1232968ad6bb334a6829af6063b753c03aa9030cfac56a9d15103"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "cdd2414a0df8a53535176a66fae4321fed5cad907b6fbd1c8d07130aa3c1f21c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "f58739945dce7beed2bc47c8c569d448b58f71fb78b8fb8fd7f047af2b1d7cf0"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "ce833775b725141172dbfaab7d46b6cd1687f65913af209f658441c545f8b04f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelly"]
    end
  end

  # No zap stanza required
end
