# This file was generated by GoReleaser. DO NOT EDIT.
cask "shelly" do
  name "shelly"
  desc "Modern CLI for controlling Shelly smart devices"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shelly"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "6133e26c293c6eb2165599dce63f98802251efd58e58fdbfad59cad3f61fef8b"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "88ec35e8048fec15445972428bd36f2fb219cd972ca1dbc0b83815a2f5db793f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "810fc2315efa394a0914045f41d1c6abc2750f681cafa39b961260e666a36342"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/shelly-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "077cfd6919b57504a8c6b7384d41f19efd05a304908328a9d792196173fe53f8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shelly"]
    end
  end

  # No zap stanza required
end
