# This file was generated by GoReleaser. DO NOT EDIT.
cask "svanhalla-cli" do
  name "svanhalla-cli"
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svanhalla-cli"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "8ad6751a38756d19e0c50dc391bafa54aea74b06ee365e3e1a6b74a4f54b4823"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "9c0e2c95c0119765ef8dd8a72a2447a05627bfbf64abbe586f61b3b537adc24e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "ac035ff988d8e06038f796fff2a657917f251388cae9f634be8f7ad650908c22"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "63e0bd510b6db2a11359b63b54506427e53e3ee650507b33b218a75b2098ab59"
    end
  end

  # No zap stanza required
end
