# This file was generated by GoReleaser. DO NOT EDIT.
cask "svanhalla-cli" do
  name "svanhalla-cli"
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svanhalla-cli"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "991248c2973a87d482eab1b5fe85502e3ebdb4355e3890f486e6102052e580b6"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "0af2204d8735819f8ec506aa4adb70a35b622fcd123948623906678555ec0aae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "8604d0093ee07e9fab7693ca1f537ae2ce873d3ec001928cc919cc8c1e30ca5c"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "52cedc8c05c679db2e6a4e8367bcf90aded2ca79a13e8f950454dcc6f15adfff"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/svanhalla-cli"]
    end
  end

  # No zap stanza required
end
