# This file was generated by GoReleaser. DO NOT EDIT.
cask "svanhalla-cli" do
  name "svanhalla-cli"
  desc "Svanhalla CLI reklamprogram"
  homepage "https://github.com/svanhalla/svanhalla-releases"
  version "1.2.15"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "svanhalla-cli"

  on_macos do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "b137a7a39c05979dd4486cf8dac134afd0d93aa349139f0e1e13e270c29d2a30"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-darwin-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "e8017591719254263509d3cc1cd2fde2f1b60652a8de872cdd2942b93a9cd54f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-amd64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "2db11a66be1c7acead481bcb67452139d393a7fbdcf9fd558a0c6e1d7b154bc5"
    end
    on_arm do
      url "https://github.com/svanhalla/svanhalla-releases/releases/download/v#{version}/svanhalla-cli-linux-arm64.tar.gz",
        verified: "github.com/svanhalla/svanhalla-releases"
      sha256 "7d03ebfb68926fcce69cc607b1a8e6744a81afef794ae7cf71a858c2f568e3cc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/svanhalla-cli"]
    end
  end

  # No zap stanza required
end
